#importamos la imagen base
FROM python:3.12-slim

#Crear carpeta de trbajo en el contenedor
WORKDIR /app

#Copiar requerimientos del proyecto 
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 

#Copiar elproyecto 
COPY ./app ./app

#Exponemos el puerto 
EXPOSE 5000

#comandos para ejecutar FastAPI
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","5000","--reload"]